### ISSUE TITLE
recommended configuration for master doesn't expose resolved leader as label

### ISSUE THREAD

**Issue by matt-deboer** [mesos/mesos_exporter#28]
in the suggested configuration for monitoring the master (i.e., `-master=leader.mesos`) none of the metrics reported (specifically `mesos_master_elected`) include the hostname/ip of the master which was elected.
This metric will also always have a value of `1` in the recommended configuration, since by definition, it is pointing at the elected leader.
It would be useful if the resolved leader ip/hostname could be included as a label....

**Comment by jpeach** [comment]
The [README](README.md) recommends running the exporter on every Mesos master and agent. In this configuration, you will get a `mesos_master_elected` metric published for each master, but only one instance of that metric will have the value of 1. This is the configuration I'm running, and it works well.
