### ISSUE TITLE
Broken travis.ci tests.

### ISSUE THREAD

**Issue by jpeach** [mesos/mesos_exporter#80]
All the travis.ci builds (Go 1.6 - 1.8) fail with the following error:

```
>> vetting code
# honnef.co/go/tools/lint/lintutil
../../../honnef.co/go/tools/lint/lintutil/util.go:273: undefined: types.SizesFor
make: *** [/home/travis/gopath/bin/staticcheck] Error 2
```

**Comment by jpeach** [comment]
Go 1.9 and 1.0 versions work correctly.

@philipnrmn @gkleiman @StephanErb I propose we just drop the older Go version from the Travis config.

**Comment by gkleiman** [comment]
SGTM
